---
version: '3'
services:
  girder:
    build:
      context: .
      dockerfile: docker/girder/Dockerfile
      args:
        entrypoint: docker/girder/entrypoint.sh
    environment:
      DOTENV_PATH: /.env
      GIRDER_MONGO_URI: mongodb://mongo/girder
    volumes:
      - .:/isic
    ports:
      - 8080:8080

  celery:
    build:
      context: .
      dockerfile: docker/girder/Dockerfile
      args:
        entrypoint: docker/celery/entrypoint.sh
    environment:
      DOTENV_PATH: /.env
      GIRDER_MONGO_URI: mongodb://mongo/girder
    volumes:
      - .:/isic

  celerybeat:
    build:
      context: .
      dockerfile: docker/girder/Dockerfile
      args:
        entrypoint: docker/celerybeat/entrypoint.sh
    environment:
      DOTENV_PATH: /.env
      GIRDER_MONGO_URI: mongodb://mongo/girder
    volumes:
      - .:/isic

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:latest
    restart: always
    ports:
      - 5672:5672

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 8025:8025

  minio:
    image: minio/minio:latest
    restart: always
    entrypoint: sh
    command: -c 'mkdir -p /minio-data/test-upload-bucket && /usr/bin/minio server /minio-data'
    environment:
      MINIO_ACCESS_KEY: accesskey
      MINIO_SECRET_KEY: secretkey
