---

- name: Install build dependencies
  apt:
    name:
      - curl
      - git
      - libffi-dev
      - build-essential
      - libgif-dev
      - libjpeg-dev
      - libssl-dev
      - zlib1g-dev
  become: yes

- name: Install Python package
  pip:
    name: "girder"
    virtualenv: "{{ python_dist_path }}"
  notify:
    - Restart Girder
    - Build Girder

- name: Deploy config file
  template:
    src: "girder.local.cfg.j2"
    dest: "/etc/girder.cfg"
  become: true
  notify: Restart Girder
