---

- name: Install Supervisor
  apt:
    name: supervisor
  become: yes

- name: Deploy Girder Supervisor config file
  template:
    src: "girder.conf.j2"
    dest: "/etc/supervisor/conf.d/girder.conf"
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: Restart Girder

- name: Deploy girder_worker Supervisor config file
  template:
    src: "worker.conf.j2"
    dest: "/etc/supervisor/conf.d/worker.conf"
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: Restart girder_worker

# TODO: this should be a handler after both
- name: Restart Supervisor for girder_worker
  service:
    name: supervisor
    state: restarted
  become: yes
