---

- name: Install Supervisor
  apt:
    name: supervisor
  sudo: yes

- name: Deploy Girder Supervisor config file
  template:
    src: "girder.conf.j2"
    dest: "/etc/supervisor/conf.d/girder.conf"
    owner: root
    group: root
    mode: 0644
  sudo: yes
  notify: Restart Supervisor
