---

- name: Install Supervisor
  apt:
    name: supervisor
  become: yes

- name: Deploy Girder Supervisor config file
  template:
    src: "girder.conf.j2"
    dest: "/etc/supervisor/conf.d/girder.conf"
    owner: root
    group: root
    mode: 0644
  become: yes
  register: result1

#- name: Add Girder Supervisor config
#  supervisorctl:
#    name: girder
#    state: present
#  become: yes
#  when: result1.changed
#  notify: Restart Girder

# TODO: Supervisor uses the wrong permissions if it's not restarted.
- service:
    name: supervisor
    state: restarted
  become: yes
  when: result1.changed
