---

- name: Install RabbitMQ
  apt:
    name: rabbitmq-server
  become: true

- name: Create RabbitMQ virtual host
  rabbitmq_vhost:
    name: "{{ rabbitmq_vhost }}"
  become: true

- name: Create RabbitMQ user
  rabbitmq_user:
    user: "{{ rabbitmq_username }}"
    password: "{{ rabbitmq_password }}"
    update_password: always
    vhost:
    permissions:
      - vhost: "{{ rabbitmq_vhost }}"
        # TODO: Determine minimal set of permissions for RabbitMQ user
        configure_priv: ".*"
        read_priv: ".*"
        write_priv: ".*"
  become: true
