---
- name: Download ISIC repo
  git:
    repo: "https://github.com/ImageMarkup/isic-archive.git"
    dest: "{{ isic_repo_path }}"
  notify:
    - Build ISIC web client
  when: not isic_repo_local

- name: Install package dependencies
  apt:
    name:
      - exiftool
      - p7zip-full
  become: true

- name: Install isic-archive package
  pip:
    # prefixing with "git+" causes Ansible to use the output of "pip list" to determine whether
    # this step is changed (even though a reinstall is always done)
    name: "git+file://{{ isic_repo_path }}#egg=isic-archive"
    # 'forcereinstall' will reinstall all packages, not just the named one, which is good for
    # making this operation as stateless as possible (i.e. new installs will end up with the same
    # package versions as existing installs)
    # 'latest' actually always reinstalls the named package, but only triggers changed
    state: "{{ 'forcereinstall' if not isic_repo_local else 'present' }}"
    editable: "{{ isic_repo_local }}"
    virtualenv: "{{ girder_virtualenv }}"
  notify:
    - Restart Girder
    - Build Girder web client

- name: Install ISIC dotenv configuration file
  template:
    src: "dotenv.j2"
    dest: "{{ ansible_user_dir }}/.girder/.env"
  notify:
    - Restart Girder

- import_tasks: worker.yml
  when: isic_worker|bool

- import_tasks: web.yml
  when: isic_web|bool
