---
- name: Download
  git:
    repo: "https://github.com/ImageMarkup/isic-archive.git"
    dest: "{{ isic_archive_path }}"
    version: "{{ isic_archive_version }}"
    clone: "{{ isic_archive_clone }}"
    update: "{{ isic_archive_update }}"
    force: "{{ isic_archive_force }}"
  notify: Build Girder web client

- name: Install package dependencies
  apt:
    name:
      - exiftool
      - p7zip-full
  become: true

- name: Install numpy
  pip:
    name: numpy
    virtualenv: "{{ girder_virtualenv }}"

- name: Install isic-archive package
  pip:
    name: "{{ isic_archive_path }}"
    editable: "{{ isic_archive_editable }}"
    virtualenv: "{{ girder_virtualenv }}"
  notify: Restart Girder

- name: Install Yarn
  npm:
    name: yarn
    global: true
    state: latest
  become: true

- name: Install ISIC GUI dependencies
  yarn:
    path: "{{ isic_archive_path }}/isic-archive-gui"

- name: Build ISIC Admin GUI
  command: yarn run build
  args:
    chdir: "{{ isic_archive_path }}/isic-archive-gui"

- name: Build ISIC Integration GUI
  command: yarn run build:integration
  args:
    chdir: "{{ isic_archive_path }}/isic-archive-gui"

- name: Create systemd drop-in unit directory for Girder
  file:
    path: "/etc/systemd/system/girder.service.d"
    state: directory
  become: true

- name: Create a systemd drop-in unit file for Girder
  template:
    src: "girder.conf.j2"
    dest: "/etc/systemd/system/girder.service.d/10-isic.conf"
  become: true
  notify: Restart Girder

- meta: flush_handlers

- include_tasks: bootstrap.yml
  vars:
    ansible_python_interpreter: "{{ girder_virtualenv }}/bin/python3"
