---

#- name: Download
#  git:
#    repo: "https://github.com/ImageMarkup/isic-archive.git"
#    dest: "{{ isic_archive_path }}"
##    version: "{{ isic_archive_version }}"
#    update: no
#    force: yes
#  notify: Build Girder

- name: Symlink
  file:
    src: "{{ isic_archive_path }}"
    dest: "{{ girder_path }}/plugins/isic_archive"
    state: link
  notify: Build Girder

- name: Install package dependencies
  apt:
    name: "{{ item }}"
  sudo: yes
  with_items:
    - p7zip-full

- name: Install Conda dependencies
  conda:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    executable: "{{ python_dist_path }}/bin/conda"
  with_items:
    - { name: numpy, version: 1.10.2 }
    - { name: scipy, version: 0.16.0 }
    - { name: scikit-image, version: 0.12.3 }
    - { name: opencv, version: 2.4.10 }

- name: Install Python dependencies
  pip:
    requirements: "{{ isic_archive_path }}/requirements.txt"
    virtualenv: "{{ python_dist_path }}"
  sudo: yes if python_dist == "system" else no

## TODO: local config
