---
- name: Download
  git:
    repo: "https://github.com/ImageMarkup/isic-archive.git"
    dest: "{{ isic_repo_path }}"
    version: "{{ isic_repo_version }}"
    clone: "{{ isic_repo_clone }}"
    update: "{{ isic_repo_update }}"
    force: "{{ isic_repo_force }}"
  notify:
    - Build ISIC web client

- name: Install package dependencies
  apt:
    name:
      - exiftool
      - p7zip-full
  become: true

- name: Install isic-archive package
  pip:
    name: "{{ isic_repo_path }}"
    editable: "{{ isic_install_editable }}"
    virtualenv: "{{ girder_virtualenv }}"
  notify:
    - Restart Girder
    - Build Girder web client

- name: Install ISIC dotenv configuration file
  template:
    src: "dotenv.j2"
    dest: "{{ ansible_user_dir }}/.girder/.env"
  notify:
    - Restart Girder

- import_tasks: worker.yml
  when: isic_worker|bool

- import_tasks: web.yml
  when: isic_web|bool
