---

- name: Download
  git:
    repo: "https://github.com/ImageMarkup/isic-archive.git"
    dest: "{{ isic_archive_path }}"
    version: "{{ isic_archive_version }}"
    clone: "{{ isic_archive_clone }}"
    update: "{{ isic_archive_update }}"
    force: "{{ isic_archive_force }}"
  notify: Build Girder

- name: Install package dependencies
  apt:
    name:
      - p7zip-full
  become: yes

- name: Install numpy
  pip:
    name: numpy
    virtualenv: "{{ python_dist_path }}"

- name: Install isic-archive package
  pip:
    name: "{{ isic_archive_path }}"
    editable: "{{ isic_archive_editable }}"
    virtualenv: "{{ python_dist_path }}"
  notify:
    - Restart Girder

- name: Install ISIC GUI dependencies
  yarn:
    path: "{{ isic_archive_path }}/isic-archive-gui"

- name: Build ISIC Admin GUI
  command: yarn run build
  args:
    chdir: "{{ isic_archive_path }}/isic-archive-gui"

- name: Build ISIC Integration GUI
  command: yarn run build:integration
  args:
    chdir: "{{ isic_archive_path }}/isic-archive-gui"

- name: Install Girder client for Girder Ansible module
  block:
    - apt:
        name: python-pip
    - pip:
        name: girder-client
  become: yes

- name: Deploy Girder systemd service
  template:
    src: girder.service.j2
    dest: "/etc/systemd/system/girder.service"
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: Restart Girder

- name: Enable Girder service
  systemd:
    name: girder
    daemon_reload: true
    state: started
    enabled: true
  become: true

- meta: flush_handlers

- name: Create admin user
  port: "{{ girder_port }}"
  girder:
    user:
      firstName: "Provision"
      lastName: "Admin"
      login: "{{ girder_admin_username }}"
      password: "{{ girder_admin_password }}"
      email: "provision.admin@isic-archive.com"
      admin: yes
    state: present

- name: Create Girder assetstore dir
  file:
    path: "{{ isic_archive_assetstore_path }}"
    owner: "{{ girder_user|default(ansible_user_id) }}"
    group: "{{ girder_user|default(ansible_user_id) }}"
    state: directory
  become: yes
  become_user: root

- name: Create assetstore
  girder:
    username: "{{ girder_admin_username }}"
    password: "{{ girder_admin_password }}"
    port: "{{ girder_port }}"
    assetstore:
      name: "Default"
      type: "filesystem"
      root: "{{ isic_archive_assetstore_path }}"
      current: true
    state: present

- name: Enable isic_archive plugin
  girder:
    username: "{{ girder_admin_username }}"
    password: "{{ girder_admin_password }}"
    port: "{{ girder_port }}"
    plugins:
      - isic_archive
      - large_image
      - worker
    state: present
  notify:
    - Restart Girder
    - Build Girder

- meta: flush_handlers

- name: Set CORS settings
  girder:
    username: "{{ girder_admin_username }}"
    password: "{{ girder_admin_password }}"
    port: "{{ girder_port }}"
    setting:
      key: "{{ item.key }}"
      value: "{{ item.value }}"
    state: present
  with_items:
    - key: "core.cors.allow_origin"
      value: "{{ isic_cors_allow_origin }}"
    - key: "core.cors.allow_methods"
      value: "{{ isic_cors_allow_methods }}"

- name: Set ISIC settings
  girder:
    username: "{{ girder_admin_username }}"
    password: "{{ girder_admin_password }}"
    port: "{{ girder_port }}"
    setting:
      key: "{{ item.key }}"
      value: "{{ item.value }}"
    state: present
  with_items:
    - key: "core.email_host"
      value: "{{ isic_email_host }}"
    - key: "core.smtp_host"
      value: "{{ isic_smtp_host }}"
    - key: "core.smtp.port"
      value: "{{ isic_smtp_port }}"
    - key: "core.smtp.username"
      value: "{{ isic_smtp_username }}"
    - key: "core.smtp.password"
      value: "{{ isic_smtp_password }}"
    - key: "core.smtp.encryption"
      value: "{{ isic_smtp_encryption }}"
    - key: "core.email_verification"
      value: "{{ isic_email_verification }}"
    - key: "isic.upload_role_arn"
      value: "{{ isic_upload_role_arn }}"
    - key: "isic.upload_bucket_name"
      value: "{{ isic_upload_bucket_name }}"

- name: Remount webroots
  girder:
    username: "{{ girder_admin_username }}"
    password: "{{ girder_admin_password }}"
    port: "{{ girder_port }}"
    setting:
      key: "core.route_table"
      value:
        core_girder: "/girder"
        core_static_root: "/static"
        markup: "/markup"
    state: present
  notify: Restart Girder
