---

#- name: Download
#  git:
#    repo: "https://github.com/ImageMarkup/isic-archive.git"
#    dest: "{{ isic_archive_path }}"
##    version: "{{ isic_archive_version }}"
#    update: no
#    force: yes
#  notify: Build Girder

- name: Install package dependencies
  apt:
    name: "{{ item }}"
  become: yes
  with_items:
    - p7zip-full

- name: Install ISIC Archive
  command: "{{ python_dist_path }}/bin/girder-install plugin -s {{ isic_archive_path }}"
  notify: Build Girder
