---
- name: Install Flower
  pip:
    name: flower
    virtualenv: "{{ girder_virtualenv }}"

- name: Ensure conf.d directory
  file:
    path: "/etc/conf.d"
    state: directory
  become: true

- name: Install Celery configurations and service files
  template:
    src: "etc/{{ item }}.j2"
    dest: "/etc/{{ item }}"
  become: true
  notify: Reload Celery
  loop:
    - "conf.d/celery"
    - "conf.d/celerybeat"
    - "systemd/system/celery.service"
    - "systemd/system/celerybeat.service"
    - "systemd/system/flower.service"

- name: Install tmpfiles.d configuration files
  template:
    src: "etc/tmpfiles.d/celery.conf.j2"
    dest: "/etc/tmpfiles.d/celery.conf"
  become: true
  register: tmpfiles

- name: Create tmpfiles
  command: systemd-tmpfiles --create
  become: true
  when: tmpfiles.changed

- name: Enable/start Celery services
  systemd:
    daemon_reload: true
    name: "{{ item }}"
    state: started
    enabled: true
  become: true
  loop:
    - celery
    - celerybeat
    - flower
