---
- name: Install flower
  pip:
    name: flower
    virtualenv: "{{ girder_virtualenv }}"

- name: Create conf.d
  file:
    path: "/etc/conf.d"
    state: "directory"
  become: true

- name: Copy celery configurations and service files
  template:
    src: "etc/{{ item }}.j2"
    dest: "/etc/{{ item }}"
  become: true
  notify: Reload Celery
  with_items:
    - "conf.d/celery"
    - "conf.d/celerybeat"
    - "systemd/system/celery.service"
    - "systemd/system/celerybeat.service"
    - "systemd/system/flower.service"

- name: Create celery user
  user:
    name: "{{ celery_user }}"
    state: present
  become: true

- name: Copy tmpfiles.d configuration
  template:
    src: "etc/tmpfiles.d/celery.conf.j2"
    dest: "/etc/tmpfiles.d/celery.conf"
  become: true
  register: tmpfiles

- name: Create tmpfiles
  command: |
    systemd-tmpfiles --create
  become: true
  when: tmpfiles.changed

- name: Enable/start celery(beat)
  systemd:
    daemon_reload: true
    name: "{{ item }}"
    state: started
    enabled: true
  become: true
  with_items:
    - celery
    - celerybeat
    - flower
