---

- name: Install build dependencies
  apt:
    name: "{{ item }}"
  become: yes
  with_items:
    - git

- name: Work around a bug in PyLibTiff
  file:
    path: "/usr/include/tiff.h"
    state: link
    src: "/usr/local/include/tiff.h"
    force: yes
  become: yes

- name: Download
  git:
    repo: "https://github.com/DigitalSlideArchive/large_image.git"
    dest: "{{ large_image_path }}"
    version: "{{ large_image_version }}"
    update: no
    force: yes
  register: result

- name: Install Large Image
  block:
    - pip:
        name: numpy
        virtualenv: "{{ python_dist_path }}"
    - command: "{{ python_dist_path }}/bin/girder-install plugin --force {{ large_image_path }}"
      notify:
        - Restart Girder
        - Build Girder
  when: result.changed
