---

- name: Install build dependencies
  apt:
    name: "{{ item }}"
  sudo: yes
  with_items:
    - git

- name: Download
  git:
    repo: "https://github.com/DigitalSlideArchive/large_image.git"
    dest: "{{ large_image_path }}"
    version: 0f463be3ea90a2bda08b80fab51eadbc42706bc2
    update: no
    force: yes
  notify: Build Girder

- name: Install Numpy
  conda:
    name: numpy
    version: 1.10.2
    executable: "{{ python_dist_path }}/bin/conda"

- name: Install Python dependencies
  pip:
    requirements: "{{ large_image_path }}/requirements.txt"
    virtualenv: "{{ python_dist_path }}"
