---

- name: Install build dependencies
  apt:
    name: "{{ item }}"
  become: yes
  with_items:
    - git

- name: Download
  git:
    repo: "https://github.com/DigitalSlideArchive/large_image.git"
    dest: "{{ large_image_path }}"
    version: "{{ large_image_version }}"
    update: no
    force: yes
  notify: Build Girder

- name: Install Numpy
  pip:
    name: numpy
    virtualenv: "{{ python_dist_path }}"

- name: Install Large Image
  command: "{{ python_dist_path }}/bin/girder-install plugin -s {{ large_image_path }}"
  notify: Build Girder
