---

- name: Add PPA key
  apt_key:
    keyserver: "keyserver.ubuntu.com"
    id: "68576280"
  become: true

- name: Add PPA
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_8.x {{ ansible_distribution_release }} main"
  become: true

- name: Install package
  apt:
    name: nodejs
  become: true

- name: Upgrade npm
  npm:
    name: npm
    global: true
    state: latest
  become: true

- name: Install Yarn
  npm:
    name: yarn
    global: true
    state: latest
  become: true
