---

- name: Ensure required variables are defined
  fail: msg="\"python_dist_path\" must be set for non-system Python distributions."
  when: (not python_dist_path) and (python_dist != "system")

- include: system.yml
  when: python_dist == "system"

- include: virtualenv.yml
  when: python_dist == "virtualenv"

- include: conda.yml
  when: python_dist == "conda"
