---

- name: Install virtualenv dependencies
  apt:
    name: "{{ item }}"
  sudo: yes
  with_items:
    - python-virtualenv

- name: Create virtualenv
  pip:
    virtualenv: "{{ python_dist_path }}"
    name: []

- name: Upgrade pip
  pip:
    name: pip
    state: latest
    virtualenv: "{{ python_dist_path }}"
