---

- name: Install virtualenv dependencies
  apt:
    name: python-virtualenv
  become: yes

- name: Create virtualenv
  pip:
    virtualenv: "{{ python_dist_path }}"
    name: []

- name: Upgrade pip
  pip:
    name: "{{ item }}"
    state: latest
    virtualenv: "{{ python_dist_path }}"
  with_items:
    - pip
    # setuptools is needed to parse the new syntax in some requirements.txt
    - setuptools
