---

- name: Install virtualenv dependencies
  apt:
    name:
      - python3-venv
      - python3-dev
      - python3-pip
  become: true

- name: Create virtualenv
  command: |
    python3.6 -m venv {{ python_dist_path }}
  args:
    creates: "{{ python_dist_path }}"

- name: Upgrade pip
  pip:
    name:
      - pip
      # setuptools is needed to parse the new syntax in some requirements.txt
      - setuptools
    state: latest
    virtualenv: "{{ python_dist_path }}"
