---

- name: Install virtualenv dependencies
  apt:
    name:
      - python-virtualenv
      - python-dev

  become: yes

- name: Upgrade pip
  pip:
    name:
      - pip
      # setuptools is needed to parse the new syntax in some requirements.txt
      - setuptools
    state: latest
    virtualenv: "{{ python_dist_path }}"
