---

- name: Add PPA key
  apt_key:
    id: "EA312927"
    keyserver: "keyserver.ubuntu.com"
  sudo: yes

- name: Add PPA
  apt_repository:
    repo: "deb https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/3.2 multiverse"
  sudo: yes

- name: Install package
  apt:
    name: mongodb-org-server
  sudo: yes
