---

- name: Add PPA key
  apt_key:
    id: "2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5"
    keyserver: "keyserver.ubuntu.com"
  become: yes

- name: Add PPA
  apt_repository:
    repo: "deb https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/3.6 multiverse"
  become: yes

- name: Install package
  apt:
    name: mongodb-org-server
  become: yes

- name: Start service
  service:
    name: mongod
    enabled: yes
    state: started
  become: yes
