---
- name: Add PPA key
  apt_key:
    id: "9DA31620334BD75D9DCB49F368818C72E52529D4"
    keyserver: "keyserver.ubuntu.com"
  become: yes

- name: Add PPA
  apt_repository:
    repo: "deb https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/4.0 multiverse"
    update_cache: yes
  become: yes

- name: Install package
  apt:
    name: mongodb-org-server
  become: yes

- name: Create Mongo data directory
  file:
    path: "{{ mongo_data_path }}"
    owner: mongodb
    group: mongodb
    state: directory
    recurse: yes
  become: yes
  become_user: root

- name: Install Mongo configuration
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
  become: yes
  become_user: root

- name: Start and enable service
  service:
    name: mongod
    enabled: yes
    state: started
  become: yes
