---
- name: Download MailHog
  get_url:
    url: "https://github.com/mailhog/MailHog/releases/download/v1.0.0/MailHog_linux_amd64"
    dest: /usr/local/bin/mailhog
    owner: root
    group: root
    mode: 0755
  become: true
  notify:
    - Restart MailHog

- name: Add MailHog basic authentication file
  copy:
    content: "{{ mailhog_username }}:{{ mailhog_password|password_hash('bcrypt') }}"
    dest: /etc/mailhog-auth
  when: mailhog_username is defined and mailhog_password is defined
  become: true
  notify:
    - Restart MailHog

- name: Deploy MailHog environment file
  template:
    src: mailhog.env.j2
    dest: /etc/mailhog.env
  become: true
  notify:
    - Restart MailHog

- name: Install MailHog service
  template:
    src: mailhog.service.j2
    dest: /etc/systemd/system/mailhog.service
  become: true
  notify:
    - Restart MailHog

- name: Start/enable MailHog
  systemd:
    name: mailhog
    daemon_reload: true
    enabled: true
  become: true
