---

- name: Install package
  apt:
    name: nginx-light
  become: true

- name: Remove default site config file
  file:
    state: absent
    path: "/etc/nginx/sites-enabled/default"
  become: true

- name: Deploy base config file
  template:
    src: "base.conf.j2"
    dest: "/etc/nginx/conf.d/base.conf"
  become: true
  notify: Restart Nginx

- name: Deploy Girder site config file
  template:
    src: girder.conf.j2
    dest: "/etc/nginx/conf.d/girder.conf"
  become: true
  notify: Restart Nginx
