---

- name: Install package
  apt:
    name: nginx-light
  become: yes

- name: Remove default site config file
  file:
    state: absent
    path: "/etc/nginx/sites-enabled/default"
  become: yes

- name: Deploy base config file
  template:
    src: "base.conf.j2"
    dest: "/etc/nginx/conf.d/base.conf"
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: Restart Nginx

- name: Deploy Girder site config file
  template:
    src: girder.conf.j2
    dest: "/etc/nginx/conf.d/girder.conf"
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: Restart Nginx

- name: Deploy supervisor site config file
  template:
    src: "supervisor.conf.j2"
    dest: "/etc/nginx/conf.d/supervisor.conf"
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: Restart Nginx
