---
- name: vagrant setup
  hosts: all

  vars:
      ansible_python_interpreter: "/usr/bin/python2.7"
      celery_broker_url: "amqp://isicarchive:password@{{ broker_ip }}/isic-archive"
      celery_result_backend: "redis://:password@{{ broker_ip }}/0"
      isic_archive_clone: false
      mongo_bind_ip: 0.0.0.0
      sentry_dsn: ""
      sentry_environment: "development"

  pre_tasks:
    - name: Install dotenv configuration file
      template:
        src: "vagrant.env.j2"
        dest: "{{ ansible_user_dir }}/.env"

  # TODO: setup SSH reverse lookup
  # TODO: set hostname
  roles:
    - role: mailhog

    - role: isic
      isic_archive_path: "{{ ansible_user_dir }}/isic_archive"
      isic_email_host: "http://isic-archive.test"
      isic_smtp_host: "{{ webserver_ip }}"
      isic_smtp_port: "1025"
      # S3 development is mocked with localstack
      isic_upload_bucket_name: "test-upload-bucket"
      isic_upload_role_arn: "fake-arn"

    - role: nginx
      site_hostname: isic-archive.test
      upstream_proxy: true

    - role: localstack
      isic_upload_bucket_name: "test-upload-bucket"
      isic_upload_role_arn: "fake-arn"
      localstack_data_dir: "{{ ansible_user_dir }}/localstack-data"
