---
- name: Setup workers
  hosts: all

  vars:
    ansible_python_interpreter: "/usr/bin/python2.7"
    celery_broker_url: "amqp://isicarchive:password@{{ broker_ip }}/isic-archive"
    celery_result_backend: "redis://:password@{{ broker_ip }}/0"
    isic_archive_assetstore_path: "{{ ansible_user_dir }}/assetstores/default"
    isic_archive_path: "{{ ansible_user_dir }}/isic_archive"
    python_dist_path: "{{ ansible_user_dir }}/env"
    sentry_dsn: ""
    sentry_environment: "development"

  pre_tasks:
    - name: Install dotenv configuration file
      template:
        src: "vagrant.env.j2"
        dest: "{{ ansible_user_dir }}/.env"

    - name: Install python, pip and virtualenv
      apt:
        name:
          - python-dev
          - python-pip
          - python-virtualenv
      become: true

    - name: Install build dependencies
      apt:
        name:
          - curl
          - git
          - libffi-dev
          - build-essential
          - libgif-dev
          - libjpeg-dev
          - libssl-dev
          - zlib1g-dev
      become: yes

    - name: Install package dependencies
      apt:
        name:
          - p7zip-full
      become: yes

    - name: Install isic-archive package
      pip:
        name: "{{ isic_archive_path }}"
        virtualenv: "{{ python_dist_path }}"
        editable: true

    # TODO: Remove when girder-worker stops depending on networkx
    - name: Install networkx==1.9.0
      pip:
        name: "networkx"
        version: "1.9.0"
        virtualenv: "{{ python_dist_path }}"

    # TODO: Remove when https://github.com/girder/girder_worker/issues/330 is resolved
    - name: Install celery==4.1.1
      pip:
        name: "celery"
        version: "4.1.1"
        virtualenv: "{{ python_dist_path }}"

    - name: Configure mongo URI
      ini_file:
        path: "{{ ansible_user_dir }}/.girder/girder.cfg"
        section: database
        option: uri
        value: '"mongodb://{{ webserver_ip }}/girder"'

  roles:
    - role: large_image
      large_image_version: "girder-3"
      large_image_virtualenv: "{{ python_dist_path }}"
      large_image_tile_sources:
        - tiff
      large_image_include_vips: true

    - role: celery
      archive_api_url: "http://isic-archive.test/api/v1"
      celery_bin: "{{ python_dist_path }}/bin/celery"
      celery_concurrency: 1
      celery_user: vagrant

  post_tasks:
    - name: Add hosts entry for isic-archive.test
      lineinfile:
        path: /etc/hosts
        line: "{{ webserver_ip }} isic-archive.test"
      become: true

    # The celery user needs to be able to write to the assetstore via tasks
    - name: Add celery user to vagrant group
      user:
        name: celery
        groups: vagrant
        append: true
      become: true

    # This is required to spin up Girder with the database pointing to prod, even
    # though workers will never use it.
    - name: Create assetstore path
      file:
        path: "{{ isic_archive_assetstore_path }}"
        state: directory

    - name: Activate virtualenv on login
      lineinfile:
        line: 'source {{ python_dist_path }}/bin/activate'
        path: "{{ ansible_user_dir }}/.profile"
        state: present

