---
- name: vagrant setup
  hosts: all

  vars:
      ansible_python_interpreter: "/usr/bin/python2.7"
      isic_archive_clone: false

  # TODO: setup SSH reverse lookup
  # TODO: set hostname
  roles:
    - role: mailhog

    - role: isic
      isic_archive_path: "{{ ansible_user_dir }}/isic_archive"
      isic_email_host: "http://isic-archive.test"
      isic_smtp_host: "localhost"
      isic_smtp_port: "1025"

    - role: nginx
      site_hostname: isic-archive.test
      upstream_proxy: true
      # S3 development is mocked with localstack
      isic_upload_bucket_name: "test-upload-bucket"
      isic_upload_role_arn: "fake-arn"

    - role: localstack

  post_tasks:
    - name: Activate virtualenv on login
      lineinfile:
        line: 'source {{ python_dist_path }}/bin/activate'
        path: "{{ ansible_user_dir }}/.profile"
        state: present

    - name: Create / remove a local girder_node_modules directory
      file:
        path: "{{ ansible_user_dir }}/girder_node_modules"
        state: "{{ 'directory' if bind_node_modules else 'absent' }}"

    - name: Mount / unmount girder_node_modules
      mount:
        path: "{{ ansible_user_dir }}/girder/node_modules"
        src: "{{ ansible_user_dir }}/girder_node_modules"
        state: "{{ 'mounted' if bind_node_modules else 'absent' }}"
        fstype: none
        opts: bind
        boot: yes
      become: yes
      become_user: root

    - name: Define WATCH_USEPOLLING environment variable
      lineinfile:
        line: "export WATCH_USEPOLLING=true"
        path: "{{ ansible_user_dir }}/.bashrc"
        state: present
