---

- name: vagrant setup
  hosts: all
  roles:
    - role: base

    - role: isic
      isic_archive_path: "{{ ansible_user_dir }}/isic_archive"

    - role: nginx
      site_hostname: isic-archive.devel
      upstream_proxy: true

    - role: supervisor
      girder_path: "{{ ansible_user_dir }}/girder"
      python_dist_path: "{{ ansible_user_dir }}/env"
