---
- name: vagrant setup
  hosts: all

  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    celery_broker_url: "amqp://isicarchive:password@{{ broker_ip }}/isic-archive"
    celery_result_backend: "redis://:password@{{ broker_ip }}/0"
    isic_archive_clone: false
    sentry_dsn: ""
    sentry_environment: "development"

  pre_tasks:
    - name: Install dotenv configuration file
      template:
        src: "vagrant.env.j2"
        dest: "{{ ansible_user_dir }}/.env"

  # TODO: setup SSH reverse lookup
  # TODO: set hostname
  roles:
    - role: mailhog

    - role: girder.mongodb
      vars:
        mongodb_version: 4.0
        mongodb_bind_public: true

    - role: girder.girder
      vars:
        # This is behind Nginx, so enable proxy mode
        girder_development_mode: false

    - role: isic
      vars:
        isic_archive_path: "{{ ansible_user_dir }}/isic_archive"
        isic_email_host: "http://isic-archive.test"
        isic_smtp_host: "{{ webserver_ip }}"
        isic_smtp_port: "1025"
        # S3 development is mocked with minio
        isic_upload_bucket_name: "test-upload-bucket"
        isic_upload_role_arn: "fake-arn"

    - role: nginx
      vars:
        site_hostname: isic-archive.test
        isic_gui_dir: "{{ ansible_user_dir }}/isic_archive/isic-archive-gui/dist"
        isic_integration_gui_dir:
          "{{ ansible_user_dir }}/isic_archive/isic-archive-gui/dist-integration"

    - role: minio
      vars:
        isic_upload_bucket_name: "test-upload-bucket"
        isic_upload_role_arn: "fake-arn"

  post_tasks:
    - name: Add hosts entry for minio
      lineinfile:
        path: /etc/hosts
        line: "127.0.0.1 minio"
      become: true

    - name: Install dev requirements
      pip:
        name: tox
        virtualenv: "{{ girder_virtualenv }}"

    - name: Activate virtualenv on login
      lineinfile:
        line: 'source {{ girder_virtualenv }}/bin/activate'
        path: "{{ ansible_user_dir }}/.profile"
        state: present
