---
- name: Setup workers
  hosts: all

  vars:
    ansible_python_interpreter: "/usr/bin/python3.6"
    celery_broker_url: "amqp://isicarchive:password@{{ broker_ip }}/isic-archive"
    celery_result_backend: "redis://:password@{{ broker_ip }}/0"
    isic_archive_assetstore_path: "{{ ansible_user_dir }}/assetstores/default"
    isic_archive_path: "{{ ansible_user_dir }}/isic_archive"
    python_dist_path: "{{ ansible_user_dir }}/env"
    sentry_dsn: ""
    sentry_environment: "development"

  pre_tasks:
    - name: Install dotenv configuration file
      template:
        src: "vagrant.env.j2"
        dest: "{{ ansible_user_dir }}/.env"

    - name: Install python, pip and virtualenv
      apt:
        name:
          - python3-dev
          - python3-pip
          - python3-venv
      become: true

    - name: Create virtualenv
      command: |
        python3.6 -m venv {{ python_dist_path }}

    - name: Install build dependencies
      apt:
        name:
          - curl
          - git
          - libffi-dev
          - build-essential
          - libgif-dev
          - libjpeg-dev
          - libssl-dev
          - zlib1g-dev
      become: true

    - name: Install package dependencies
      apt:
        name:
          - p7zip-full
      become: true

    - name: Install numpy
      pip:
        name: numpy
        virtualenv: "{{ python_dist_path }}"

    - name: Install isic-archive package
      pip:
        name: "{{ isic_archive_path }}"
        virtualenv: "{{ python_dist_path }}"
        editable: true

    - name: Configure mongo URI
      ini_file:
        path: "/etc/girder.cfg"
        section: database
        option: uri
        value: '"mongodb://{{ webserver_ip }}/girder"'
      become: true

  roles:
    - role: large_image
      vars:
        large_image_version: "girder-3"
        large_image_virtualenv: "{{ python_dist_path }}"
        large_image_tile_sources:
          - tiff
        large_image_include_vips: true

    - role: celery
      vars:
        archive_api_url: "http://isic-archive.test/api/v1"
        celery_bin: "{{ python_dist_path }}/bin/celery"
        celery_concurrency: 1
        celery_user: vagrant

  post_tasks:
    - name: Add hosts entry for isic-archive.test
      lineinfile:
        path: /etc/hosts
        line: "{{ webserver_ip }} isic-archive.test"
      become: true

    # The celery user needs to be able to write to the assetstore via tasks
    - name: Add celery user to vagrant group
      user:
        name: celery
        groups: vagrant
        append: true
      become: true

    # This is required to spin up Girder with the database pointing to prod, even
    # though workers will never use it.
    - name: Create assetstore path
      file:
        path: "{{ isic_archive_assetstore_path }}"
        state: directory

    - name: Activate virtualenv on login
      lineinfile:
        line: 'source {{ python_dist_path }}/bin/activate'
        path: "{{ ansible_user_dir }}/.profile"
        state: present
