---

- name: Install build dependencies
  apt:
    name: "{{ item }}"
  sudo: yes
  with_items:
    - git
    - libjpeg-dev
    - zlib1g-dev
    - libssl-dev

- name: Download
  git:
    repo: "https://github.com/girder/girder_worker.git"
    dest: "{{ worker_path }}"
    version: "{{ worker_version }}"
    update: yes
    force: yes

- name: Install Pillow
  conda:
    name: Pillow
    version: 3.2.0
    executable: "{{ python_dist_path }}/bin/conda"

- name: Install Python dependencies
  pip:
    requirements: "{{ item }}"
    virtualenv: "{{ python_dist_path }}"
  sudo: yes if python_dist == "system" else no
  with_items:
    - "{{ worker_path }}/requirements.txt"
    - "{{ worker_path }}/girder_worker/plugins/girder_io/requirements.txt"

- name: Deploy config file
  template:
    src: "worker.local.cfg.j2"
    dest: "{{ worker_path }}/girder_worker/worker.local.cfg"
