---

- name: Install build dependencies
  apt:
    name: "{{ item }}"
  become: yes
  with_items:
    - git
    - libjpeg-dev
    - zlib1g-dev
    - libssl-dev

- name: Download
  git:
    repo: "https://github.com/girder/girder_worker.git"
    dest: "{{ worker_path }}"
    version: "{{ worker_version }}"
    update: yes
    force: yes

- name: Install Python package
  pip:
    name: "{{ worker_path }}[girder_io]"
    editable: true
    virtualenv: "{{ python_dist_path }}"

- name: Deploy config file
  template:
    src: "worker.local.cfg.j2"
    dest: "{{ worker_path }}/girder_worker/worker.local.cfg"
