---

- name: Install build dependencies
  apt:
    name:
      - git
      - libjpeg-dev
      - zlib1g-dev
      - libssl-dev
  become: yes

- name: Download
  git:
    repo: "https://github.com/girder/girder_worker.git"
    dest: "{{ worker_path }}"
    version: "{{ worker_version }}"
    update: yes
    force: yes
  register: result

- name: Install Python package
  pip:
    name: "{{ worker_path }}[girder_io]"
#    editable: true
    # TODO: The 'editable' option is broken until Ansible 2.4
    # See: https://github.com/ansible/ansible/pull/19688
    extra_args: '-e'
    virtualenv: "{{ python_dist_path }}"
  when: result.changed
  notify:
    - Restart girder_worker
    - Restart Girder
    - Build Girder

- name: Deploy config file
  template:
    src: "worker.local.cfg.j2"
    dest: "{{ worker_path }}/girder_worker/worker.local.cfg"
  notify: Restart girder_worker
