---
dependencies:
  - role: girder.girder
    vars:
      girder_daemonize: "{{ isic_server }}"
      girder_web: "{{ isic_web }}"

  - role: large_image
    vars:
      large_image_virtualenv: "{{ girder_virtualenv }}"
      large_image_tile_sources:
        - tiff
      large_image_include_vips: true
