---

- name: Install awscli
  pip:
    name: awscli
    virtualenv: "{{ girder_virtualenv }}"

- name: Download minio
  get_url:
    url: https://dl.minio.io/server/minio/release/linux-amd64/minio
    dest: /opt/minio
    mode: 0775
  become: true

- name: Daemonize minio
  template:
    src: "minio.service.j2"
    dest: "/etc/systemd/system/minio.service"
  become: true

- name: Start minio
  systemd:
    name: minio
    daemon_reload: true
    enabled: true
    state: started
  become: true

- name: Wait for minio to be listening
  wait_for:
    port: 9000
    timeout: 20

- name: Create default bucket
  file:
    path: "{{ ansible_user_dir }}/minio-data/{{ isic_upload_bucket_name }}"
    state: directory
