---

- listen: Restart Supervisor
  service:
    name: supervisor
    state: restarted
  become: yes

- listen: Restart Girder
  supervisorctl:
    name: girder
    state: restarted
  become: yes

- listen: Restart Girder
  wait_for:
    port: "{{ girder_port }}"
    state: started
    timeout: 20

- name: Restart girder_worker
  supervisorctl:
    name: worker
    state: restarted
  become: yes
